-- MySQL Script generated by MySQL Workbench
-- Wed Jul 18 12:15:17 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bdd_bilal
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bdd_bilal
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bdd_bilal` DEFAULT CHARACTER SET utf8 ;
USE `bdd_bilal` ;

-- -----------------------------------------------------
-- Table `bdd_bilal`.`adminUser`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdd_bilal`.`adminUser` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdd_bilal`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdd_bilal`.`category` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdd_bilal`.`post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdd_bilal`.`post` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NULL,
  `content` VARCHAR(45) NULL,
  `date` VARCHAR(45) NULL,
  `adminUser_id` INT NOT NULL,
  `category_id` INT NOT NULL,
  PRIMARY KEY (`id`, `adminUser_id`, `category_id`),
  CONSTRAINT `fk_post_adminUser1`
    FOREIGN KEY (`adminUser_id`)
    REFERENCES `bdd_bilal`.`adminUser` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_post_category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `bdd_bilal`.`category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;




-- -----------------------------------------------------
-- Table `bdd_bilal`.`comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdd_bilal`.`comment` (
  `id` INT NOT NULL,
  `author` VARCHAR(45) NULL,
  `content` VARCHAR(45) NULL,
  `date` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `post_id` INT NOT NULL,
  `post_adminUser_id` INT NOT NULL,
  PRIMARY KEY (`id`, `post_id`, `post_adminUser_id`),
  CONSTRAINT `fk_comment_post1`
    FOREIGN KEY (`post_id` , `post_adminUser_id`)
    REFERENCES `bdd_bilal`.`post` (`id` , `adminUser_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;