-- MySQL Script generated by MySQL Workbench
-- Tue Jul 17 19:57:45 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bilalweb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bilalweb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bilalweb` DEFAULT CHARACTER SET utf8 ;
USE `bilalweb` ;

-- -----------------------------------------------------
-- Table `bilalweb`.`posts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bilalweb`.`posts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(70) NULL,
  `content` LONGTEXT NULL,
  `publish` VARCHAR(70) NULL,
  `resume` LONGTEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bilalweb`.`moderators`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bilalweb`.`moderators` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fullname` VARCHAR(70) NULL,
  `username` VARCHAR(70) NULL,
  `password` VARCHAR(70) NULL,
  `posts_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_moderators_posts1`
    FOREIGN KEY (`posts_id`)
    REFERENCES `bilalweb`.`posts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;



-- -----------------------------------------------------
-- Table `bilalweb`.`visitors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bilalweb`.`visitors` (
  `id` INT NOT NULL,
  `fullname` VARCHAR(70) NULL,
  `email` VARCHAR(70) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bilalweb`.`notifications`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bilalweb`.`notifications` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `notifiable_id` VARCHAR(70) NULL,
  `notifiable_type` VARCHAR(70) NULL,
  `visitors_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_notifications_visitors1`
    FOREIGN KEY (`visitors_id`)
    REFERENCES `bilalweb`.`visitors` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;



-- -----------------------------------------------------
-- Table `bilalweb`.`comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bilalweb`.`comments` (
  `id` INT NOT NULL,
  `message` LONGTEXT NULL,
  `status` VARCHAR(45) NULL,
  `posts_id` INT NOT NULL,
  `visitors_id` INT NOT NULL,
  `notifications_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_comments_posts1`
    FOREIGN KEY (`posts_id`)
    REFERENCES `bilalweb`.`posts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comments_visitors1`
    FOREIGN KEY (`visitors_id`)
    REFERENCES `bilalweb`.`visitors` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comments_notifications1`
    FOREIGN KEY (`notifications_id`)
    REFERENCES `bilalweb`.`notifications` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;




-- -----------------------------------------------------
-- Table `bilalweb`.`messages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bilalweb`.`messages` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `content` LONGTEXT NULL,
  `visitors_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_messages_visitors1`
    FOREIGN KEY (`visitors_id`)
    REFERENCES `bilalweb`.`visitors` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;



-- -----------------------------------------------------
-- Table `bilalweb`.`tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bilalweb`.`tags` (
  `id` INT NOT NULL,
  `name` VARCHAR(70) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bilalweb`.`settings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bilalweb`.`settings` (
  `id` INT NOT NULL,
  `site_name` VARCHAR(45) NULL,
  `post_per_page` VARCHAR(45) NULL,
  `under_maintenance` VARCHAR(45) NULL,
  `prevent_commentings` VARCHAR(45) NULL,
  `tags_visibility` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bilalweb`.`post_tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bilalweb`.`post_tags` (
  `posts_id` INT NOT NULL,
  `tags_id` INT NOT NULL,
  CONSTRAINT `fk_post_tags_posts1`
    FOREIGN KEY (`posts_id`)
    REFERENCES `bilalweb`.`posts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_post_tags_tags1`
    FOREIGN KEY (`tags_id`)
    REFERENCES `bilalweb`.`tags` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;




SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
