


<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Nouvel article</title>

<!-- Bootstrap -->
    <!-- MD Bootstrap 4.5.4 -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="../vendor/fontawesome-free-5.1.0-web/css/fontawesome.css">
    <!-- Bootstrap core CSS -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet">
    <!-- Material Design Bootstrap -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.5.4/css/mdb.min.css" rel="stylesheet">
<!-- Chosen -->
    <link rel="stylesheet" type="text/css" href="../vendor/chosen_v1.8.7/chosen.min.css" />
<!-- Summernote -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.9/summernote-lite.css" rel="stylesheet">
<!-- CSS -->
    <link rel="stylesheet" type="text/css" href="css/default.css" />
    <link rel="stylesheet" type="text/css" href="css/new-article.css" />


</head>

<body>


<div class="container-fluid display-table">
    <div class="row display-table-row">
        <!-- side menu -->
        <div class="col-md-2 col-sm-1 d-none d-md-block display-table-cell valing-top" id="side-menu">
            <h1 class="d-none d-lg-block">Navigation</h1>
            <ul>
                <li class="link">
                    <a href="index.html">
                        <i class="fa fa-th" aria-hidden="true"></i>
                        <span class="d-none d-md-block">Tableau de bord</span>
                    </a>
                </li>

                <li class="link active">
                    <a href="#collapse-post" data-toggle="collapse" aria-controls="collapse-post">
                        <i class="fa fa-list-alt" aria-hidden="true"></i>
                        <span class="d-none d-md-block">Article</span>
                        <span class="badge badge-success pull-right d-none d-lg-block">20</span>
                    </a>
                    <ul class="collapse collapseable" id="collapse-post">
                        <li>
                            <a href="new-article.html">Nouvel article</a>
                        </li>
                        <li>
                            <a href="articles.html">Mes articles</a>
                        </li>
                    </ul>
                </li>

                <li class="link">
                    <a href="#collapse-comments" data-toggle="collapse" aria-controls="collapse-coments">
                        <i class="fa fa-pencil" aria-hidden="true"></i>
                        <span class="d-none d-md-block">Commentairess</span>
                    </a>
                    <ul class="collapse collapseable" id="collapse-comments">
                        <li>
                            <a href="approved.html">Approuvé
                                <span class="badge badge-success pull-right d-none d-lg-block">10</span>
                            </a>
                        </li>

                        <li>
                            <a href="approved.html">Désapprouvés
                                <span class="badge badge-warning pull-right d-none d-lg-block">10</span>
                            </a>
                        </li>
                    </ul>
                </li>

                <li class="link">
                    <a href="commenters.html">
                        <i class="fa fa-user" aria-hidden="true"></i>
                        <span class="d-none d-md-block">Rédacteurs</span>
                    </a>
                </li>

                <li class="link">
                    <a href="tags.html">
                        <i class="fa fa-tags" aria-hidden="true"></i>
                        <span class="d-none d-md-block">Tags</span>
                    </a>
                </li>

                <li class="link settings-btn">
                    <a href="settings.html">
                        <i class="fa fa-cog" aria-hidden="true"></i>
                        <span class="d-none d-md-block">Paramètres</span>
                    </a>
                </li>
            </ul>
        </div>
        <!-- main content area -->
        <div class="col-md-10 col-sm-11 display-table-cell valing-top box">
            <header class="row clearfix" id="nav-header">
                <div class="col-sm-5">
                    <div class="navbar-default pull-left">

                        <!-- ICI : BOUTON HAMBURGER POUR LE RESPONSIVE -->
                    </div>
                    <input type="text" class="d-none d-lg-block" id="header-search-field" placeholder="Rechercher...">
                </div>
                <div class="col-sm-7">
                    <ul class="pull-right">
                        <li id="welcome" class="d-none d-sm-block" >Bienvenue sur votre admin</li>
                        <li class="fixed-width">
                            <a href="#">
                                <i class="fa fa-bell" aria-hidden="true"></i>
                                <!-- <i class="fa fa-warning" aria-hidden="true">3</i> -->
                                <span class="badge badge-warning" aria-hidden="true">3</span>
                            </a>
                        </li>
                        <li class="fixed-width">
                            <a href="#">
                                <i class="fa fa-envelope-open" aria-hidden="true"></i>
                                <!-- <i class="fa fa-comment" aria-hidden="true">3</i> -->
                                <span class="badge badge-success" aria-hidden="true">3</span>
                            </a>
                        </li>
                        <li>
                            <a href="#" class="logout">
                                <i class="fa fa-sign-out" aria-hidden="true"></i>
                                Quitter
                            </a>
                        </li>
                    </ul>
                </div>
            </header>

                <div id="content">
                    <header>
                        <h2 class="page_title">Créer un nouvel article</h2>
                    </header>

                    <div class="content-inner">
                        <div class="form-wrapper">
                            <form>
                                <div class="form-group">
                                    <label class="sr-only">Title</label>
                                    <input type="text" class="form-control" id="title" placeholder="Titre">
                                </div>

                                <div class="form-group">
                                    <label class="sr-only">Tags</label>
                                    <select data-placeholder="Sélectionnez vos tags" multiple name="tags" class="form-control chosen-select">
                                        <option></option>
                                        <option>anecdote</option>
                                        <option>flash</option>
                                        <option>réflexion</option>
                                        <option>shoot</option>
                                    </select>
                                </div>

                                <div class="form-group">
                                    <label class="sr-only">Article</label>
                                    <textarea class="form-control summernote" placeholder="Article" name="article"></textarea>
                                </div>

                                <div class="checkbox">
                                    <label>
                                        <input type="checkbox"><span class="info">  publier l'article lorsque je clique sur enregistrer</span>
                                    </label>
                                </div>

                                <div class="clearfix">
                                    <button type="submit" class="btn btn-primary pull-right">Enregistrer / Publier</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <footer id="admin-footer" class="clearfix">
                        <div class="pull-left"><b>Copyright </b>&copy; 2018</div>
                        <div class="pull-right">admin system</div>
                    </footer>
                </div>
        </div>

    </div>
</div>

            

<!--**************** SCRIPTS ****************-->

<script type="javascript" src="../js/script.js"></script>


<!-- MD Bootstrap  -->
    <!-- JQuery -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <!-- Bootstrap tooltips -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.13.0/umd/popper.min.js"></script>
    <!-- Bootstrap core JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <!-- MDB core JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.5.4/js/mdb.min.js"></script>
<!-- Chosen jQuery -->
    <script src="../vendor/chosen_v1.8.7/chosen.jquery.min.js"></script>
<!-- Summernote JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.9/summernote-lite.js"></script>

    <script src="js/default.js"></script>

    <script type="text/javascript">
        var config = {
            '.chosen-select' : {},
            '.chosen-select-deselect' : {allow_single_deselect: true},
            '.chosen-select-no-single': {disable_search_threshold: 10},
            '.chosen-select-no-result': {no_results_text: 'Oops, nothing found!'},
            '.chosen-select-width': {width: "95%"}
        }
        for (var selector in config) {
            $(selector).chosen(config[selector]);
        }
    </script>

    <script type="text/javascript">
        $('.summernote').summernote({
        placeholder: 'Liberez votre écriture...',
        tabsize: 2,
        height: 200
      });
    </script>

<!--**************** /SCRIPTS ****************-->

</body>
</html>